[workspace]
members = ["d2fps", "d2interface", "bin_patch", "bin_patch_mac"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
debug = true
panic = "abort"
lto = "thin"
codegen-units = 1
