[package]
name = "bin_patch"
version = "0.1.0"
edition = "2021"

[dependencies.bin_patch_mac]
path = "../bin_patch_mac"

[dependencies.windows-sys]
version = "0.48.0"
features = ["Win32_Foundation", "Win32_System_Memory"]
