use crate::{module::Ordinal::Ordinal, Addresses};

pub use crate::v102::{
  DyPos, Entity, EntityTable, EntityTables, GameCursor, Room, StaticPos, BASE_ADDRESSES,
};

pub const ADDRESSES: Addresses = Addresses {
  player: 0x1450c0,
  env_effects: 0x12e83c,
  game_type: 0x12eac8,
  entity_table: 0x1438c0,
  entity_table2: 0x1444c0,
  client_loop_globals: 0x12e8b8,
  // Doesn't exist in this version
  apply_pos_change: 0x0,
  in_perspective: Ordinal(10012),
  hwnd: Ordinal(10029),
  server_update_time: 0xc17a4,
  draw_menu: Ordinal(10015),
  cursor_table: 0x11acd0,
  game_cursor: 0x168078,
  summit_cloud_x_pos: 0,
  draw_line: Ordinal(10061),
  find_closest_color: Ordinal(10030),
  viewport_width: 0,
  viewport_height: 0,
  viewport_shift: 0x134594,
};

pub mod dtbl {
  pub use crate::v102::dtbl::*;
  use crate::{
    dtbl::{ByEqComponent, I32Code, ItemCode, Missile},
    ArmorTy, BodyLoc, Component, HitClass, Id16, Range, Size,
  };

  #[repr(C)]
  pub struct PerVendor {
    pub akara: u8,
    pub gheed: u8,
    pub charsi: u8,
    pub fara: u8,
    pub lysander: u8,
    pub drognan: u8,
    pub hralti: u8,
    pub alkor: u8,
    pub ormus: u8,
    pub elzix: u8,
    pub asheara: u8,
    pub cain: u8,
    pub halbu: u8,
    pub jamella: u8,
    pub malah: u8,
    pub larzuk: u8,
    pub anya: u8,
  }

  #[repr(C)]
  pub struct ItemDef {
    pub completed: u8,
    pub rarity: u8,
    pub lvl: u8,
    pub dmg: Range<u8>,
    pub dmg_miss: Range<u8>,
    pub dmg_2h: Range<u8>,
    pub melee_range: u8,
    pub str_bonus: u8,
    pub dex_bonus: u8,
    pub armor: Range<i32>,
    pub req_str: u8,
    pub req_dex: u8,
    pub absorbs: u8,
    pub inv_size: Size<u8>,
    pub block: u8,
    pub durability: u8,
    pub indestructible: u8,
    pub missile: u8,
    pub replenish: u8,
    pub special: u8,
    pub component: Component,
    pub body_locs: [BodyLoc; 2],
    pub armor_gfx: ByEqComponent<ArmorTy>,
    pub two_handed: u8,
    pub useable: u8,
    pub ty: u8,
    pub sub_ty: u8,
    pub sound: u8,
    pub unique: u8,
    pub quest: u8,
    pub transparent: u8,
    pub trans_tbl: u8,
    pub throwable: u8,
    pub _pad0: [u8; 1],
    pub light_size: u8,
    pub belt: u8,
    pub auto_belt: u8,
    pub quivered: u8,
    pub stackable: u8,
    pub spawnable: u8,
    pub missile_ty: Id16<Missile>,
    pub spell_icon: u8,
    pub dur_warning: u8,
    pub qnt_warning: u8,
    pub has_sockets: u8,
    pub socket_count: u8,
    pub transmogrify: u8,
    pub tmog_qnt: Range<u8>,
    pub _pad1: [u8; 1],
    pub hit_class: HitClass,
    pub multi_handed: u8,
    pub transform: u8,
    pub inv_trans: u8,
    pub weapon_group_enum: u8,
    pub weapon_speed_enum: u8,
    pub speed: i32,
    pub bitfield1: i32,
    pub cost: i32,
    pub stack_size: Range<u32>,
    pub spell_offset: i32,
    pub gem_offset: i32,
    pub code: ItemCode,
    pub alt_gfx: I32Code,
    pub uber_code: ItemCode,
    pub wclass: I32Code,
    pub wclass_2h: I32Code,
    pub group: [u8; 15],
    pub tmog_ty: ItemCode,
    pub name: [u8; 64],
    pub wname: [u16; 64],
    pub flippy_file: [u8; 32],
    pub inv_file: [u8; 32],
    pub uinv_file: [u8; 32],
    pub better_gem: ItemCode,
    pub skip_name: u8,
    pub vend_qnt: Range<PerVendor>,
    pub vend_mqnt: Range<PerVendor>,
    pub vend_mlvl: PerVendor,
    pub nm_upg: u8,
    pub hell_upg: u8,
    pub can_sell_out: u8,
  }
}
