[package]
name = "bin_patch_mac"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
proc-macro = true

[dependencies.xxhash-rust]
version = "0.8.6"
features = ["xxh3"]
